const stage = {
	panel: [
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: true, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: true, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: true, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: true, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
		{ isDead: false, turn: [1, 2, 11] },
	],
	max: 13,
	min: 3,
	row: 5,
};
export default stage;
