export const translations = {
	en: {
		back: "Back",
		reset: "Reset",
		cancel: "Cancel",
		turn: "",
		count: "Turns",
		adCount: "Remaining",
		congratulations: "Congratulations!",
		clearText: " creared! Tap the level up button to advance to the next level",
		watchAdsText: "Would you like to watch an ad and reset the panel?",
		levelDownAlert: "Are you sure you want to lower the level?",
		levelDown: "Lower the level",
		nextAds: "Would you like to watch an ad and take it to the next level?",
		wacthAds: "Watch an ad",
		errorHappend: "An error has occurred",
		errorRetry: "Please check your network and try again.",
		hint: "Tips!",
		hintText: "First, try tapping from the smallest number.",
		allStageClearText:
			"Congratulations on clearing level 5 !!! Actually, We thought that it was impossible to clear level 5. If you share it on social media and we find it, We may want to update this app that adds even higher difficulty!",
		timeup: "Would you like to watch an ad and add more turns?",
		doAgree: "Do you agree with the Terms of Service and Privacy Policy?",
		agree: "I agree",
		tos: "Terms of Service and Privacy Policy",
		tosURL: "https://regenerate-eight.vercel.app/en/tos",
		notReadyToAd:
			"Currently, we are not ready to serve ads, so the features are released for free.",
		notReadyToAdText:
			"Please note that this is a temporary measure and ads will be displayed as soon as they are ready.",
	},
	ja: {
		back: "戻る",
		reset: "リセット",
		cancel: "キャンセル",
		turn: "ターン",
		count: "経過ターン数",
		adCount: "あと",
		congratulations: "おめでとう！",
		clearText:
			"をクリアしました! Lv. upボタンをタップして次のレベルに進みましょう!",
		watchAdsText: "広告を視聴してパネルをリセットしますか？",
		levelDownAlert: "レベルを下げてよろしいですか？",
		levelDown: "レベルを下げる",
		nextAds: "広告を視聴して次のレベルに進みますか？",
		wacthAds: "広告を視聴する",
		errorHappend: "エラーが発生しました。",
		errorRetry: "通信環境を確認して再度お試しください。",
		hint: "ヒント",
		hintText: "まずは小さい数字から順にタップしてみよう！",
		allStageClearText:
			"レベル5のクリアおめでとうございます!!!実は開発者はレベル5のクリアは不可能だと思っていました。SNSでシェアすると、もし開発者がそれを見つけた場合、さらに上の難易度を追加するアップデートを行いたくなるかもしれませんよ!",
		timeup: "広告を視聴して残りターン数を追加しますか？",
		doAgree: "利用規約とプライバシーポリシーに同意しますか？",
		agree: "同意する",
		tos: "利用規約とプライバシーポリシー",
		tosURL: "https://regenerate-eight.vercel.app/ja/tos",
		notReadyToAd:
			"現在、広告を配信する用意が整っていないため、無料で機能が解放されています。",
		notReadyToAdText:
			"これは一時的な措置であり、準備が整い次第広告が表示されるようになりますので、ご了承ください。",
	},
};
